### PR TITLE
Persistent objects: save handle information

### LINKED ISSUE #785: Issues in creating and opening persistent objects.
Hi, I'm currently developing some basic code to get used to the GP API's and I tried to create a simple example where I allocate an transient object to which I generate a key and associate a persistent object. The problem comes when I close the persistent object, I think some information is not being saved because when I open it again to allocate an cipher init operation it does not have the same `objectType` nor the same `objectSize`. It finishes with `error code 0xffff000a`.

I tried to look at the secure UART to find some information but the only thing I useful I got was:

`TEE-CORE: INFO:    USER-TA: Failed to allocate an operation: 0xffff000a` 

I saw that this error is associated with:

> The requested operation is valid but not supported in this implementation.

The thing is if I use the `transient_key` when I allocate the cipher operation it works just fine.

This is the code I used in TA:

```
static TEE_Result key_generation(void)
{
	TEE_Result result = TEE_SUCCESS;
	TEE_ObjectHandle transient_key = (TEE_ObjectHandle)NULL;
	TEE_ObjectHandle persistent_key = (TEE_ObjectHandle)NULL;
	TEE_ObjectHandle key = (TEE_ObjectHandle)NULL;
	TEE_OperationHandle encrypt_op = (TEE_OperationHandle)NULL;
	TEE_ObjectInfo keyInfo;
	TEE_ObjectInfo keyInfo2;
	TEE_ObjectInfo keyInfo3;
	uint32_t alg = TEE_ALG_AES_CBC_NOPAD;
	void *IV = NULL;
	size_t IVlen = 16;

	size_t key_size = 256;
	uint32_t objectID = 1;	
	uint32_t flags = TEE_DATA_FLAG_ACCESS_READ | TEE_DATA_FLAG_ACCESS_WRITE | TEE_DATA_FLAG_ACCESS_WRITE_META | TEE_DATA_FLAG_SHARE_READ | TEE_DATA_FLAG_SHARE_WRITE; 	

	result = TEE_AllocateTransientObject(TEE_TYPE_AES, key_size, &transient_key);

	if (result != TEE_SUCCESS) {
		IMSG("Failed to Allocate transient object handle : 0x%x", result);
		goto cleanup1;
	}

	IMSG("Transient object for AES key allocated with success.\n");
	
	result = TEE_GenerateKey(transient_key, key_size, (TEE_Attribute *)NULL, 0);

	if (result != TEE_SUCCESS) {
		IMSG("Failed to generate a transient key: 0x%x", result);
		goto cleanup2;
	}

	IMSG("AES-256 key generated with success.\n");

	TEE_GetObjectInfo(transient_key, &keyInfo);

	IMSG("Key Info - objectType: %x, objectUsage:  %x, objectSize: %d, maxObjectSize: %d, handleFlags:%x, datasize: %d, dataposition: %d\n", keyInfo.objectType, keyInfo.objectUsage, keyInfo.objectSize, keyInfo.maxObjectSize, keyInfo.handleFlags, keyInfo.dataSize, keyInfo.dataPosition);

	result = TEE_CreatePersistentObject(TEE_STORAGE_PRIVATE, &objectID, sizeof(objectID), flags, transient_key, NULL, 0, &persistent_key);

	if (result != TEE_SUCCESS) {
		IMSG("Failed to create a persistent key: 0x%x", result);
		goto cleanup2;
	}

	IMSG("Persistent object for AES key allocated with success.\n");

	TEE_GetObjectInfo(persistent_key, &keyInfo2);

	IMSG("Key Info2 - objectType: %x, objectUsage:  %x, objectSize: %d, maxObjectSize: %d, handleFlags:%x  datasize: %d, dataposition: %d\n", keyInfo2.objectType, keyInfo2.objectUsage, keyInfo2.objectSize, keyInfo2.maxObjectSize, keyInfo2.handleFlags, keyInfo2.dataSize, keyInfo2.dataPosition);

	TEE_CloseObject(persistent_key);

	result = TEE_OpenPersistentObject(TEE_STORAGE_PRIVATE, &objectID, sizeof(objectID), flags, &key);

	if (result != TEE_SUCCESS) {
		IMSG("Failed to open persistent key: 0x%x", result);
		goto cleanup2;
	}	

	TEE_GetObjectInfo(key, &keyInfo3);

	IMSG("Key Info3 - objectType: %x, objectUsage:  %x, objectSize: %d, maxObjectSize: %d, handleFlags:%x  datasize: %d, dataposition: %d\n", keyInfo3.objectType, keyInfo3.objectUsage, keyInfo3.objectSize, keyInfo3.maxObjectSize, keyInfo3.handleFlags, keyInfo3.dataSize, keyInfo3.dataPosition);

	result = TEE_AllocateOperation(&encrypt_op, alg, TEE_MODE_ENCRYPT, keyInfo3.maxObjectSize);

	if (result != TEE_SUCCESS) {
		IMSG("Failed to allocate an operation: 0x%x", result);
		goto cleanup3;
	}

	result = TEE_SetOperationKey(encrypt_op, key);

	if (result != TEE_SUCCESS) {
		IMSG("Failed to set operation key: 0x%x", result);
		goto cleanup4;
	}

	IV = TEE_Malloc(IVlen, 0);

	if (!IV) 
	{
		IMSG("Out of memory for IV.");
		goto cleanup4;
	}

	TEE_CipherInit(encrypt_op, IV, IVlen);

	TEE_Free(IV);

	cleanup4:
		TEE_FreeOperation(encrypt_op);
	cleanup3:
		TEE_CloseObject(key);
	cleanup2:
		TEE_FreeTransientObject(transient_key);	
	cleanup1:
		return result;
}
```

And this is what I got from the secure UART:

```
DEBUG:   [0x0] TEE-CORE:tee_ta_init_static_ta_session:159:    Lookup for Static TA f894e6e0-1215-11e6-92810002a5d5c51b
DEBUG:   [0x0] TEE-CORE:init_session_with_signed_ta:629:    Load dynamic TA
DEBUG:   [0x0] TEE-CORE:ta_load:398: Loaded TA at 0xff200000
DEBUG:   [0x0] TEE-CORE:ta_load:399: ELF load address 0x80001000
DEBUG:   [0x0] TEE-CORE:init_session_with_signed_ta:635:       dyn TA : f894e6e0-1215-11e6-92810002a5d5c51b
ERROR:   TEE-CORE: INFO:    USER-TA: Transient object for AES key allocated with success.
ERROR:   TEE-CORE: INFO:    USER-TA: AES-256 key generated with success.
ERROR:   TEE-CORE: INFO:    USER-TA: Key Info - objectType: a0000010, objectUsage:  ffffffff, objectSize: 256, maxObjectSize: 256, handleFlags:20000, datasize: 0, dataposition: 0
DEBUG:   [0x0] TEE-CORE:create_tee_file:1390: Creating TEE file=E0E694F81512E61192810002A5D5C51B/.01000000
DEBUG:   [0x0] TEE-CORE:ree_fs_open:1488: file=E0E694F81512E61192810002A5D5C51B/.01000000, length=0
DEBUG:   [0x0] TEE-CORE:ree_fs_ftruncate_internal:1651: Ignore due to file length does not changed
DEBUG:   [0x0] TEE-CORE:ree_fs_write:1888: E0E694F81512E61192810002A5D5C51B/.01000000, data len=16
DEBUG:   [0x0] TEE-CORE:out_of_place_write:1289: Write data, offset: 0, size_to_write: 16
DEBUG:   [0x0] TEE-CORE:write_data_to_block:1196: Write 16 bytes to block0
DEBUG:   [0x0] TEE-CORE:flush_block_to_storage:1002: Successfully encrypt and write block0 to storage, size=52
DEBUG:   [0x0] TEE-CORE:remove_outdated_block:679: remove outdated block0
DEBUG:   [0x0] TEE-CORE:__remove_block_file:662: E0E694F81512E61192810002A5D5C51B/.01000000/block0.1
DEBUG:   [0x0] TEE-CORE:ree_fs_write:1888: E0E694F81512E61192810002A5D5C51B/.01000000, data len=36
DEBUG:   [0x0] TEE-CORE:read_block_from_storage:972: Successfully read and decrypt block0 from storage, size=52
DEBUG:   [0x0] TEE-CORE:out_of_place_write:1289: Write data, offset: 16, size_to_write: 36
DEBUG:   [0x0] TEE-CORE:write_data_to_block:1196: Write 36 bytes to block0
DEBUG:   [0x0] TEE-CORE:flush_block_to_storage:1002: Successfully encrypt and write block0 to storage, size=52
DEBUG:   [0x0] TEE-CORE:remove_outdated_block:679: remove outdated block0
DEBUG:   [0x0] TEE-CORE:__remove_block_file:662: E0E694F81512E61192810002A5D5C51B/.01000000/block0.0
DEBUG:   [0x0] TEE-CORE:ree_fs_rename:1967: old=E0E694F81512E61192810002A5D5C51B/.01000000, new=E0E694F81512E61192810002A5D5C51B/01000000
DEBUG:   [0x0] TEE-CORE:create_hard_link:1325: E0E694F81512E61192810002A5D5C51B/.01000000/block0.1 -> E0E694F81512E61192810002A5D5C51B/01000000/block0.1
DEBUG:   [0x0] TEE-CORE:create_hard_link:1325: E0E694F81512E61192810002A5D5C51B/.01000000/meta.0 -> E0E694F81512E61192810002A5D5C51B/01000000/meta.0
DEBUG:   [0x0] TEE-CORE:unlink_tee_file:1336: file=E0E694F81512E61192810002A5D5C51B/.01000000
DEBUG:   [0x0] TEE-CORE:unlink_tee_file:1352: unlink E0E694F81512E61192810002A5D5C51B/.01000000/meta.0
DEBUG:   [0x0] TEE-CORE:unlink_tee_file:1352: unlink E0E694F81512E61192810002A5D5C51B/.01000000/block0.1
DEBUG:   [0x0] TEE-CORE:open_tee_file:1417: Opening TEE file=E0E694F81512E61192810002A5D5C51B/01000000
DEBUG:   [0x0] TEE-CORE:ree_fs_open:1488: file=E0E694F81512E61192810002A5D5C51B/01000000, length=52
DEBUG:   [0x0] TEE-CORE:ree_fs_lseek:1574: offset=52, whence=1
ERROR:   TEE-CORE: INFO:    USER-TA: Persistent object for AES key allocated with success.
DEBUG:   [0x0] TEE-CORE:open_tee_file:1417: Opening TEE file=E0E694F81512E61192810002A5D5C51B/01000000
DEBUG:   [0x0] TEE-CORE:ree_fs_open:1488: file=E0E694F81512E61192810002A5D5C51B/01000000, length=52
ERROR:   TEE-CORE: INFO:    USER-TA: Key Info2 - objectType: a0000010, objectUsage:  ffffffff, objectSize: 0, maxObjectSize: 0, handleFlags:30000  datasize: 0, dataposition: 0
DEBUG:   [0x0] TEE-CORE:open_tee_file:1417: Opening TEE file=E0E694F81512E61192810002A5D5C51B/01000000
DEBUG:   [0x0] TEE-CORE:ree_fs_open:1488: file=E0E694F81512E61192810002A5D5C51B/01000000, length=52
DEBUG:   [0x0] TEE-CORE:ree_fs_read:1787: E0E694F81512E61192810002A5D5C51B/01000000, data len=16
DEBUG:   [0x0] TEE-CORE:ree_fs_read:1792: start_block_num:0, end_block_num:0
DEBUG:   [0x0] TEE-CORE:ree_fs_read:1804: block_num:0, offset:0, size_to_read: 16
DEBUG:   [0x0] TEE-CORE:read_block_from_storage:972: Successfully read and decrypt block0 from storage, size=52
DEBUG:   [0x0] TEE-CORE:read_data_from_block:1210: Read 16 bytes from block0
DEBUG:   [0x0] TEE-CORE:ree_fs_read:1787: E0E694F81512E61192810002A5D5C51B/01000000, data len=36
DEBUG:   [0x0] TEE-CORE:ree_fs_read:1792: start_block_num:0, end_block_num:0
DEBUG:   [0x0] TEE-CORE:ree_fs_read:1804: block_num:0, offset:16, size_to_read: 36
DEBUG:   [0x0] TEE-CORE:read_block_from_storage:972: Successfully read and decrypt block0 from storage, size=52
DEBUG:   [0x0] TEE-CORE:read_data_from_block:1210: Read 36 bytes from block0
DEBUG:   [0x0] TEE-CORE:open_tee_file:1417: Opening TEE file=E0E694F81512E61192810002A5D5C51B/01000000
DEBUG:   [0x0] TEE-CORE:ree_fs_open:1488: file=E0E694F81512E61192810002A5D5C51B/01000000, length=52
DEBUG:   [0x0] TEE-CORE:ree_fs_lseek:1574: offset=52, whence=1
DEBUG:   [0x0] TEE-CORE:open_tee_file:1417: Opening TEE file=E0E694F81512E61192810002A5D5C51B/01000000
DEBUG:   [0x0] TEE-CORE:ree_fs_open:1488: file=E0E694F81512E61192810002A5D5C51B/01000000, length=52
ERROR:   TEE-CORE: INFO:    USER-TA: Key Info3 - objectType: 0, objectUsage:  ffffffff, objectSize: 0, maxObjectSize: 0, handleFlags:30000  datasize: 0, dataposition: 0
ERROR:   TEE-CORE: INFO:    USER-TA: Failed to allocate an operation: 0xffff000a
DEBUG:   [0x0] TEE-CORE:tee_ta_invoke_command:561:   => Error: ffff000a of 4
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:317: tee_ta_close_session(0xff056100)
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:336:    ... Destroy session
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:355:    ... Destroy TA ctx
```

I'm so sorry for the long message but I tried for a long time to solve this but I can't. If someone could help me I would be very thankfull.

### PR DESCRIPTION
**Pull request by pascal-brand-st-dev**
When creating a Persistent Object (TEE_CreatePersistentObject)
using an object handle, the information and attributes related
to the handle are saved.

The information are restored when opening the object
(TEE_OpenPersistentObject)

Fixes #785

Signed-off-by: Pascal Brand <pascal.brand@st.com>

### CODE REVIEW

File: core/tee/tee_svc_storage.c [hunk 1]
```diff
@@ -77,6 +77,8 @@ struct tee_svc_storage_head {
 	uint32_t head_size;
 	uint32_t meta_size;
 	uint32_t ds_size;
+	TEE_ObjectInfo info;
```
Comment (jenswi-linaro) [inline core/tee/tee_svc_storage.c]: This saves redundant or unneeded information in the persistent object. I would prefer to just add the needed fields from `TEE_ObjectInfo`.

File: core/tee/tee_svc_storage.c [hunk 2]
```diff
@@ -330,6 +332,8 @@ static TEE_Result tee_svc_storage_read_head(struct tee_ta_session *sess,
 
 	o->data_size = head.meta_size;
 	o->info.dataSize = head.ds_size;
+	o->info = head.info;
```
Comment (jenswi-linaro) [inline core/tee/tee_svc_storage.c]: Overwrites `o->info.dataSize` assigned above.

**Comment by pascal-brand-st-dev** [comment]
updated

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`
