### PR TITLE
Fix des3_cbc_mac in case of 112bits key

### LINKED ISSUE #408: TEE_MACInit panics when using des3 112bit key
Hi,

Has anybody tested DES3 using 112bit key?

I have tested on juno but it doesn't seem to work.

To be specific, I was testing MAC API and TEE_MACInit panicked when using des3 112bit key.

I tried to find out what went wrong and I found that DES3 only allows a key of length, 24 bytes (24 * 7 = 168 bits) rejecting any other key length.

in core/lib/libtomcrypt/src/ciphers/des.c

int des3_setup(const unsigned char *key, int keylen, int num_rounds, symmetric_key *skey)
{

...

    if (keylen != 24) {
        return CRYPT_INVALID_KEYSIZE;
    }

...

}

My question here is..
is this a bug  or 112 bit key is not supported just yet?

### PR DESCRIPTION
**Pull request by pascal-brand-st-dev**
In DES3, a key of 112 bits is made of 2 56 bits keys.
DES3 can be run using only 2 56 bit keys, with the 3rd
key being equal to the first.

Fix #408

Signed-off-by: Pascal Brand <pascal.brand@st.com>

### CODE REVIEW

File: core/lib/libtomcrypt/src/tee_ltc_provider.c [hunk 1]
```diff
@@ -2168,6 +2168,11 @@ static TEE_Result mac_init(void *ctx, uint32_t algo, const uint8_t *key,
 	int ltc_cipherindex;
 #endif
 #if defined(CFG_CRYPTO_CBC_MAC)
+	uint8_t *real_key;
+	uint8_t key_array[24];
+	size_t real_key_len;
+#endif
```
Comment (jenswi-linaro) [inline core/lib/libtomcrypt/src/tee_ltc_provider.c]: This `#endif` and following `#if` can be removed.

**Comment by pascal-brand-st-dev** [comment]
Updated

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```
