### PR TITLE
ta: pkcs11: be flexible on RSA private key optional attributes

### LINKED ISSUE #5418: pkcs11_1021 fails when OP-TEE core is configured with MBedTLS
Test platform QEMUv8 with `make CFG_CRYPTOLIB_NAME=mbedtls CFG_CRYPTOLIB_DIR=lib/libmbedtls run`:

```
$ xtest pkcs11_1021
Test ID: pkcs11_1021
Run test suite with level=0

TEE test application started over default TEE instance
######################################################
#
# regression+gp+pkcs11
#
######################################################

* pkcs11_1021 PKCS11: RSA PKCS key generation and signing
o pkcs11_1021.1 RSA-1024: Generate key pair
pkcs11_1000.c:6439: rv has an unexpected value: 0x6 = CKR_FUNCTION_FAILED, expected 0x0 = CKR_OK
  pkcs11_1021.1 FAILED
  pkcs11_1021 FAILED
+-----------------------------------------------------
Result of testsuite regression+gp+pkcs11 filtered by "pkcs11_1021":
pkcs11_1021.1 FAILED first error at pkcs11_1000.c:6439
pkcs11_1021 FAILED
+-----------------------------------------------------
8 subtests of which 1 failed
1 test case of which 1 failed
2307 test cases were skipped
TEE test application done!
```
Secure console has:
```
E/TA:  tee2pkcs_add_attribute:379 Failed TEE attribute 0xc0000630 for 0x126/EXPONENT_1
```

`0xc0000630` is `TEE_ATTR_RSA_EXPONENT1` which is one of the RSA CRT parameters, optional as per the GP spec.

With this patch:
```diff
diff --git a/ta/pkcs11/src/processing.c b/ta/pkcs11/src/processing.c
index 08374513..835f3b28 100644
--- a/ta/pkcs11/src/processing.c
+++ b/ta/pkcs11/src/processing.c
@@ -336,8 +336,10 @@ enum pkcs11_rc alloc_get_tee_attribute_data(TEE_ObjectHandle tee_obj,
        uint32_t sz = 0;

        res = TEE_GetObjectBufferAttribute(tee_obj, attribute, NULL, &sz);
-       if (res != TEE_ERROR_SHORT_BUFFER)
+       if (res != TEE_ERROR_SHORT_BUFFER) {
+               TEE_Panic(0xBADBEEF);
                return PKCS11_CKR_FUNCTION_FAILED;
+       }

        ptr = TEE_Malloc(sz, TEE_USER_MEM_HINT_NO_FILL_ZERO);
        if (!ptr)
```
...the following stack trace is produced:
```
E/TC:? 0 TA panicked with code 0xbadbeef
E/LD:  Status of TA fd02c9da-306c-48c7-a49c-bbd827ae86ee
E/LD:   arch: aarch64
E/LD:  region  0: va 0x40004000 pa 0x0e326000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x40006000 pa 0x0e328000 size 0x008000 flags r-xs (ldelf)
E/LD:  region  2: va 0x4000e000 pa 0x0e330000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x4000f000 pa 0x0e331000 size 0x004000 flags rw-s (ldelf)
E/LD:  region  4: va 0x40013000 pa 0x0e335000 size 0x001000 flags r--s
E/LD:  region  5: va 0x40014000 pa 0x0e36e000 size 0x002000 flags rw-s (stack)
E/LD:  region  6: va 0x40016000 pa 0x7bcf9000 size 0x001000 flags rw-- (param)
E/LD:  region  7: va 0x40017000 pa 0x7bcba000 size 0x001000 flags rw-- (param)
E/LD:  region  8: va 0x40023000 pa 0x00001000 size 0x02a000 flags r-xs [0] .ta_head .text .eh_frame .rodata .gnu.hash .dynsym .dynstr .hash .rela.dyn
E/LD:  region  9: va 0x4004d000 pa 0x0002b000 size 0x00e000 flags rw-s [0] .dynamic .got .rela.got .data .bss
E/LD:   [0] fd02c9da-306c-48c7-a49c-bbd827ae86ee @ 0x40023000 (optee_os/out/arm/ta/pkcs11/fd02c9da-306c-48c7-a49c-bbd827ae86ee.elf)
E/LD:  Call stack:
E/LD:   0x4002b4c8 alloc_get_tee_attribute_data at optee_os/ta/pkcs11/src/processing.c:340
E/LD:   0x4002b56c tee2pkcs_add_attribute at optee_os/ta/pkcs11/src/processing.c:366
E/LD:   0x4002f2ac tee2pkcs_rsa_attributes at optee_os/ta/pkcs11/src/processing_rsa.c:514
E/LD:   0x4002b900 entry_generate_key_pair at optee_os/ta/pkcs11/src/processing.c:512
E/LD:   0x40023d70 TA_InvokeCommandEntryPoint at optee_os/ta/pkcs11/src/entry.c:350
E/LD:   0x40038730 entry_invoke_command at optee_os/lib/libutee/arch/arm/user_ta_entry.c:370
E/LD:   0x400318d8 __ta_entry at optee_os/out/arm/export-ta_arm64/src/user_ta_header.c:48
```
...which makes me think the bug is in the PKCS#11 TA which doesn't expect the attribute to be absent (actually, `TEE_GetObjectBufferAttribute()` returns `TEE_SUCCESS` with `sz == 0` which would indicate `TEE_ATTR_RSA_EXPONENT1` is present but equal to zero? weird... but in any case we don't have a non-zero attribute so the code in `alloc_get_tee_attribute_data()` looks wrong).

@etienne-lms any idea?

### PR DESCRIPTION
**Pull request by etienne-lms**
Allow RSA private key to partially store the RSA private key optional attributes without facing complaints from the GP TEE API.
    
On one hand, in the PKCS#11 specification, RSA private key attributes CKA_PRIME_1, CKA_PRIME_2, CKA_EXPONENT_1, CKA_EXPONENT_2 and CKA_COEFFICIENT are optional and the spec does not add much constraints on their presence.
In the other hand, the GP TEE Internal Core API requests that these 5 optional attributes are all present or none is present at all.

As a trade-off, allow PKCS#11 client to partially provide them but do not load them into the TEE object unless they are all present.

This change requires that PKCS#11 attributes related to NULL pointers or nul byte size are not loaded in a GP TEE object hence a preparatory commit in this series.

Fixes #5418 and **~~hopefully also~~** #7520 (https://github.com/OP-TEE/optee_os/issues/7520#issuecomment-3289363368).

### CODE REVIEW

**Comment by etienne-lms** [comment]
Successfully tested with `xtest -t pkcs11 -l 15` with a standard build config (ltc in core) and with libmbedtls in core (`CFG_CRYPTOLIB_NAME=mbedtls CFG_CRYPTOLIB_DIR=lib/libmbedtls`).

**Review by dlansky1 — APPROVED** [review]

File: ta/pkcs11/src/processing_rsa.c [hunk 1]
```diff
@@ -591,9 +585,15 @@ enum pkcs11_rc load_tee_rsa_key_attrs(TEE_Attribute **tee_attrs,
 				       obj, PKCS11_CKA_COEFFICIENT))
 			count++;
 
-		if (count == 8)
-			rc = PKCS11_CKR_OK;
+		/*
+		 * As mentioned above, if at least 1of these optional
```
Comment (jenswikl) [inline ta/pkcs11/src/processing_rsa.c]: s/at least 1of/any of/

File: ta/pkcs11/src/processing_rsa.c [hunk 2]
```diff
@@ -559,18 +558,13 @@ enum pkcs11_rc load_tee_rsa_key_attrs(TEE_Attribute **tee_attrs,
...
-			break;
-		if (rc == PKCS11_RV_NOT_FOUND || !a_ptr) {
-			rc = PKCS11_CKR_OK;
-			break;
-		}
-
-		rc = PKCS11_CKR_GENERAL_ERROR;
 
+		/*
+		 * If pre-computed values are present load those
```
Comment (jenswikl) [inline ta/pkcs11/src/processing_rsa.c]: If the pre-computed CRT parameters are present, load them

**Comment by jforissier** [comment]
@etienne-lms I tested the same configuration as you.

`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (vexpress-qemu_armv8a)`

**Comment by etienne-lms** [comment]
~~@dlansky, if you approve this change, could you post a comment with your `Review-by` or `Acked-by` tag (see for example https://github.com/OP-TEE/optee_os/pull/7203#issuecomment-2574537836) so I can add it into each commit message?~~

**(edited) Excuse-me @dlansky, I used a wrong Github account name :confused:**

**Comment by etienne-lms** [comment]
@dlansky1, if you approve this change, could you post a comment with your `Review-by` or `Acked-by` tag (see for example https://github.com/OP-TEE/optee_os/pull/7203#issuecomment-2574537836) so I can add it into each commit message?

**Comment by dlansky1** [comment]
Review-by: Dedy Lansky <quic_dlansky@quicinc.com>

**Comment by jenswikl** [comment]
For "ta: pkcs11: be flexible on RSA private key optional attributes", please apply:
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
@Emantor, @vesajaaskelainen, @maroueneboubakri, could you have a look at this change? Especially the 1st commit. I think it's 100% valid but another review is welcome.

CI build failure (QEMUv8, Hafnium) is unrelated.

**Comment by Emantor** [comment]
Hi, if I read the code correctly than this works around the fact that we may have a zero sized TEE object stored for the specific attribute. This makes sense for the already existing wrongly stored objects, but how do we handle the case where we want to modify said wrongly stored attribute for an object?

**Comment by vesajaaskelainen** [comment]
About wrongly stored objects -- only hack we have is that very early PKCS#11 TA's caused empty CKA_ALLOWED_MECHANISMS fields. and for that we have a hack for already deployed products.

Otherwise there has been zero issues with attributes.

For this hack commit I have comment `Upstream-Status: Inappropriate [does not match PKCS#11 standard]`.

**Comment by vesajaaskelainen** [comment]
This GP API issue is somewhat annoying... I would even fix the API. There are couple of cases where there is no actual need for extra parameters -- ie. not really needed for math operation.

File: ta/pkcs11/src/processing_rsa.c [hunk 3]
```diff
@@ -559,18 +558,13 @@ enum pkcs11_rc load_tee_rsa_key_attrs(TEE_Attribute **tee_attrs,
...
-			break;
-		if (rc == PKCS11_RV_NOT_FOUND || !a_ptr) {
-			rc = PKCS11_CKR_OK;
-			break;
-		}
-
-		rc = PKCS11_CKR_GENERAL_ERROR;
 
+		/*
+		 * If the pre-computed CTR parameters are present load them
```
Comment (etienne-lms) [inline ta/pkcs11/src/processing_rsa.c]: Typo: s/CTR/CRT/

File: ta/pkcs11/src/processing_rsa.c [hunk 4]
```diff
@@ -559,18 +558,13 @@ enum pkcs11_rc load_tee_rsa_key_attrs(TEE_Attribute **tee_attrs,
...
 
-		/* If pre-computed values are present load those */
-		rc = get_attribute_ptr(obj->attributes, PKCS11_CKA_PRIME_1,
-				       &a_ptr, NULL);
-		if (rc != PKCS11_CKR_OK && rc != PKCS11_RV_NOT_FOUND)
-			break;
-		if (rc == PKCS11_RV_NOT_FOUND || !a_ptr) {
-			rc = PKCS11_CKR_OK;
-			break;
-		}
```
Comment (etienne-lms) [inline ta/pkcs11/src/processing_rsa.c:570]: If you're reluctant in merging the generic change in ta/pkcs11/src/pkcs11_helpers.c (1st commit), I can propose to discard it and change the sequence above, testing one by one if the 5 non-empty CRT attributes are found.

E.g.:
```c
static enum pkcs11_rc count_rsa_crt_parameters(struct pkcs11_object *obj)
{
	const uint32_t crt_attr[] = {
		PKCS11_CKA_PRIME_1, PKCS11_CKA_PRIME_2, PKCS11_CKA_EXPONENT_1,
		PKCS11_CKA_EXPONENT_2, PKCS11_CKA_COEFICIENT,
	};
	enum pkcs11_rc rc = PKCS11_CKR_GENERAL_ERROR;
￼	void *a_ptr = NULL;
	size_t a_size = 0;
	size_t count = 0;
	size_t n = 0;

	for (n = 0; n <ARRAY_SIZE(crt_attr); n++) {
		rc = get_attribute_ptr(obj->attributes, crt_attr[n], &a_ptr, &a_size);
		if (rc == PKCS11_RV_NOT_FOUND)
			return rc;
		if (rc != PKCS11_CKR_OK)
			return rc;
		if (a_ptr && a_size)
			count++;
	}

	if (count != ARRAY_SIZE(crt_attr))
		return PKCS11_RV_NOT_FOUND;

	return PKCS11_CKR_OK
}
```
and here:
```c
		/*
		 * If the pre-computed CTR parameters are present ...
		 */
		rc = count_rsa_crt_parameters(obj);
		if (rc != PKCS11_CKR_OK) {
			if (rc == PKCS11_RV_NOT_FOUND)
				rc = PKCS11_CKR_OK;
			break;
		}

		rc = PKCS11_CKR_GENERAL_ERROR;

		if (pkcs2tee_load_attr(&attrs[count], TEE_ATTR_RSA_PRIME1, obj,
				       PKCS11_CKA_PRIME_1))
			count++;

		...

**Comment by vesajaaskelainen** [comment]
I am trying to understand the problem that is being addressed in here -- if I understood correctly one could say that OP-TEE mbedtls port is not GP/OP-TEE internal compliant or am I mistaken?

It feels a bit weird that we would need to think about differences in internal API behavior in TA side.

**Comment by etienne-lms** [comment]
> I am trying to understand the problem that is being addressed in here -- if I understood correctly one could say that OP-TEE mbedtls port is not GP/OP-TEE internal compliant or am I mistaken?

I would rather say that when libtomcrypt is core main crypto lib, OP-TEE does not comply with RCT params requirements of the GP TEE specs. When libmbedtls is used as core main crypto lib, OP-TEE better complies with this requirements, but I would not say it fully complies. I did not try loading e.g. only PRIME_1/2 and not the 3 others.

> It feels a bit weird that we would need to think about differences in internal API behavior in TA side.

You are based on somewhat normative APIs so we have to deal with them. Indeed PKCS#11 and GP TEE core API do not 100% match.

**Comment by vesajaaskelainen** [comment]
> > I am trying to understand the problem that is being addressed in here -- if I understood correctly one could say that OP-TEE mbedtls port is not GP/OP-TEE internal compliant or am I mistaken?
> 
> I would rather say that when libtomcrypt is core main crypto lib, OP-TEE does not comply with RCT params requirements of the GP TEE specs. When libmbedtls is used as core main crypto lib, OP-TEE better complies with this requirements, but I would not say it fully complies. I did not try loading e.g. only PRIME_1/2 and not the 3 others.
> 
> > It feels a bit weird that we would need to think about differences in internal API behavior in TA side.
> 
> You are based on somewhat normative APIs so we have to deal with them. Indeed PKCS#11 and GP TEE core API do not 100% match.

My point here is that now that we have tested that it works nicely -- and out of sudden it does not work if someone goes to twiddle with OP-TEE's configuration.

One could expect that if you create TA that is tested with OP-TEE then developer of such TA should not need to test with all configuration variations.

But if this is wanted then I hope that needed configuration variantions are part of standard test suite runs so that if there are problems then those are captured.

**Comment by jforissier** [comment]
> But if this is wanted then I hope that needed configuration variantions are part of standard test suite runs so that if there are problems then those are captured.

Yes they are. Both LibTomCrypt (default core crypto library) and MBed TLS are tested as part of my release test suite. In fact I had an exception to cater for this bug, which I have now removed. See https://github.com/jforissier/optee_release_tests/commit/919579830b83aa74eed22dbe758237ffa883f750.

**Comment by vesajaaskelainen** [comment]
Next question is would we rather like to make libtomcrypt and mbedtels adapters to behave in similar fashion or start adapting the difference?

**Comment by jforissier** [comment]
> Next question is would we rather like to make libtomcrypt and mbedtels adapters to behave in similar fashion or start adapting the difference?

Good point. MBedTLS is lacking compared to LibTomCrypt, and most of the time we have worked around the limitations (typically by pulling the missing feature out of LibTomCrypt) but some differences remain (as this PR shows). In my opinion, and ideally, both configs should be mostly indistinguishable from the outside (GP API).

**Comment by etienne-lms** [comment]
I've discarded commit "ta: pkcs11: empty attributes should not be loaded into TEE objects" that got no review tags
and implemented my proposal https://github.com/OP-TEE/optee_os/pull/7528#discussion_r2355448336.

**Comment by etienne-lms** [comment]
@Emantor: your comment https://github.com/OP-TEE/optee_os/pull/7528#issuecomment-3299129473 is addressed in the way I've discard**ed** the related commit in this P-R.

@vesajaaskelainen, is the change fine to you?
@dlansky1, maybe you would like **~~the~~ to** test the latest version of this P-R.
@jenswi-linaro, @jforissier, I've not applied your review tags since I modified the change content.

**Comment by jforissier** [comment]
My Tested-by still stands.

**Comment by vesajaaskelainen** [comment]
> @Emantor: your comment [#7528 (comment)](https://github.com/OP-TEE/optee_os/pull/7528#issuecomment-3299129473) is addressed in the way I've discard**ed** the related commit in this P-R.
> 
> @vesajaaskelainen, is the change fine to you? @dlansky1, maybe you would like **~the~ to** test the latest version of this P-R. @jenswi-linaro, @jforissier, I've not applied your review tags since I modified the change content.

I trust that you checked GP API requirement for all or none of the optional properties.

As for the change itself small nit about the name `count_rsa_crt_parameters` as this is not really counting from callers point of view.

Perhaps something like:
- can_load_rsa_crt_parameters
- check_load_rsa_crt_parameters
- contains_all_rsa_crt_parameters
- valid_rsa_crt_parameters

or something like that.

**Comment by etienne-lms** [comment]
Ok, I've change to `contains_all_rsa_crt_parameters()`.

**Comment by vesajaaskelainen** [comment]
`Reviewed-by: Vesa Jääskeläinen <vesa.jaaskelainen@vaisala.com>`

**Comment by jforissier** [comment]
Taking this in the release as a bug fix.
